name: Build

on: workflow_dispatch

permissions:
  contents: write

env:
  REL_VERSION: v2.5.307

jobs:
  build:
    name: Build and create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Disable DEV Flag + Set Version
      run: |
        sudo apt-get install jq -y
        mv package.json pkg-temp.json
        jq --arg vs "$REL_VERSION" -r '. + {dev:false, version:$vs}' pkg-temp.json > package.json
        rm pkg-temp.json
        cat package.json
    - name: Build Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dev/build/Dockerfile
        tags: |
          fsinfo/wiki:canary
          fsinfo/wiki:canary-${{ env.REL_VERSION }}
    - name: Extract compiled files
      run: |
        mkdir -p _dist
        docker create --name wiki fsinfo/wiki:canary-$REL_VERSION
        docker cp wiki:/wiki _dist
        docker rm wiki
        rm _dist/wiki/config.yml
        cp ./config.sample.yml _dist/wiki/config.sample.yml
        find _dist/wiki/ -printf "%P\n" | tar -czf wiki-js.tar.gz --no-recursion -C _dist/wiki/ -T -
    - name: Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        name: ${{ env.REL_VERSION }}
        tag_name: ${{ env.REL_VERSION }}
        files: wiki-js.tar.gz
